services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"  # 開発ポート3000をマッピング
    volumes:
      - .:/app
      - /app/node_modules  # node_modulesのボリュームをコンテナ内に保持
    networks:
      - default
    command: yarn dev  # 開発モードでの起動コマンド
